"""add_macro_cache_table

Revision ID: 509fe2882c0c
Revises: 31e76b4a1363
Create Date: 2026-03-22 15:49:09.920270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509fe2882c0c'
down_revision: Union[str, Sequence[str], None] = '31e76b4a1363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_cache',
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_cache')
    # ### end Alembic commands ###
