"""add_ism_manufacturing_tables

Revision ID: ddad14618553
Revises: 509fe2882c0c
Create Date: 2026-03-23 12:02:07.151620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddad14618553'
down_revision: Union[str, Sequence[str], None] = '509fe2882c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ism_mfg_report',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pmi', sa.Float(), nullable=True),
    sa.Column('new_orders', sa.Float(), nullable=True),
    sa.Column('production', sa.Float(), nullable=True),
    sa.Column('employment', sa.Float(), nullable=True),
    sa.Column('supplier_deliveries', sa.Float(), nullable=True),
    sa.Column('inventories', sa.Float(), nullable=True),
    sa.Column('customers_inventories', sa.Float(), nullable=True),
    sa.Column('prices', sa.Float(), nullable=True),
    sa.Column('backlog_of_orders', sa.Float(), nullable=True),
    sa.Column('new_export_orders', sa.Float(), nullable=True),
    sa.Column('imports', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('ism_mfg_industry_rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['ism_mfg_report.date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'component', 'industry', name='uq_ism_rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ism_mfg_industry_rank')
    op.drop_table('ism_mfg_report')
    # ### end Alembic commands ###
